In [4]:
#np.sort
import numpy as np
a=np.random.randint(1,100,15)
a

array([25, 55, 32, 53, 20, 41, 57, 29, 50, 19, 50, 70, 75, 52, 74])

In [5]:
b=np.random.randint(1,100,24).reshape(6,4)

In [6]:
np.sort(a)

array([19, 20, 25, 29, 32, 41, 50, 50, 52, 53, 55, 57, 70, 74, 75])

In [11]:
b

array([[19, 10, 44, 40],
       [54, 77, 36, 45],
       [ 9, 33, 95, 16],
       [ 8,  1, 85, 57],
       [82, 70, 89, 83],
       [27, 53, 94, 80]])

In [10]:
np.sort(b)
np.sort(b,axis=0) #column wise
np.sort(b,axis=1)

array([[10, 19, 40, 44],
       [36, 45, 54, 77],
       [ 9, 16, 33, 95],
       [ 1,  8, 57, 85],
       [70, 82, 83, 89],
       [27, 53, 80, 94]])

In [13]:
#np.append
np.append(a,200)

array([ 25,  55,  32,  53,  20,  41,  57,  29,  50,  19,  50,  70,  75,
        52,  74, 200])

In [15]:
b

array([[19, 10, 44, 40],
       [54, 77, 36, 45],
       [ 9, 33, 95, 16],
       [ 8,  1, 85, 57],
       [82, 70, 89, 83],
       [27, 53, 94, 80]])

In [20]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[19., 10., 44., 40.,  1.],
       [54., 77., 36., 45.,  1.],
       [ 9., 33., 95., 16.,  1.],
       [ 8.,  1., 85., 57.,  1.],
       [82., 70., 89., 83.,  1.],
       [27., 53., 94., 80.,  1.]])

In [21]:
#np.concatenate
c=np.arange(6).reshape(2,3)
d=np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [22]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [23]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [24]:
#np.unique
e=np.array([1,1,2,2,3,3,4,4,5,5,6,6])


In [25]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

In [26]:
#np.expand_dims
#we can get the expanded dimensions of an array

a

array([25, 55, 32, 53, 20, 41, 57, 29, 50, 19, 50, 70, 75, 52, 74])

In [28]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [30]:
np.expand_dims(a,axis=1)

array([[25],
       [55],
       [32],
       [53],
       [20],
       [41],
       [57],
       [29],
       [50],
       [19],
       [50],
       [70],
       [75],
       [52],
       [74]])

In [32]:
#np.where
a

array([25, 55, 32, 53, 20, 41, 57, 29, 50, 19, 50, 70, 75, 52, 74])

In [34]:
#find all indices with value greater than 50

np.where(a>50)

(array([ 1,  3,  6, 11, 12, 13, 14]),)

In [35]:
#replace all values > 50 with 0

np.where(a>50,0,a)

array([25,  0, 32,  0, 20, 41,  0, 29, 50, 19, 50,  0,  0,  0,  0])

In [37]:
np.where(a%2==0,0,a)

array([25, 55,  0, 53,  0, 41, 57, 29,  0, 19,  0,  0, 75,  0,  0])

In [38]:
#np.argmax
a

array([25, 55, 32, 53, 20, 41, 57, 29, 50, 19, 50, 70, 75, 52, 74])

In [39]:
np.argmax(a)

12

In [41]:
np.argmax(b,axis=0)

array([4, 1, 2, 4])

In [43]:
np.argmax(b,axis=1)

array([2, 1, 2, 2, 2, 2])

In [44]:
#np.argmin
np.argmin(a)

9

#np.cumsum

In [45]:
a

array([25, 55, 32, 53, 20, 41, 57, 29, 50, 19, 50, 70, 75, 52, 74])

In [46]:
np.cumsum(a)

array([ 25,  80, 112, 165, 185, 226, 283, 312, 362, 381, 431, 501, 576,
       628, 702])

In [47]:
b

array([[19, 10, 44, 40],
       [54, 77, 36, 45],
       [ 9, 33, 95, 16],
       [ 8,  1, 85, 57],
       [82, 70, 89, 83],
       [27, 53, 94, 80]])

In [48]:
np.cumsum(b)

array([  19,   29,   73,  113,  167,  244,  280,  325,  334,  367,  462,
        478,  486,  487,  572,  629,  711,  781,  870,  953,  980, 1033,
       1127, 1207])

In [49]:
np.cumsum(b,axis=0)

array([[ 19,  10,  44,  40],
       [ 73,  87,  80,  85],
       [ 82, 120, 175, 101],
       [ 90, 121, 260, 158],
       [172, 191, 349, 241],
       [199, 244, 443, 321]])

In [51]:
np.cumsum(b,axis=1) #0-column 1->row

array([[ 19,  29,  73, 113],
       [ 54, 131, 167, 212],
       [  9,  42, 137, 153],
       [  8,   9,  94, 151],
       [ 82, 152, 241, 324],
       [ 27,  80, 174, 254]])

In [52]:
a

array([25, 55, 32, 53, 20, 41, 57, 29, 50, 19, 50, 70, 75, 52, 74])

In [53]:
np.cumprod(a)

array([                  25,                 1375,                44000,
                    2332000,             46640000,           1912240000,
               108997680000,        3160932720000,      158046636000000,
           3002886084000000,   150144304200000000, -7936642779709551616,
       -4952398119510719488,   729714817376309248, -1341335735281770496])

In [55]:
#np.percentile used to compute percentile
a


array([25, 55, 32, 53, 20, 41, 57, 29, 50, 19, 50, 70, 75, 52, 74])

In [56]:
np.percentile(a,100)

75.0

In [57]:
np.percentile(a,0)

19.0

In [58]:
np.percentile(a,50)

50.0

In [60]:
np.median(a)

50.0

#np.histogram

In [61]:
a

array([25, 55, 32, 53, 20, 41, 57, 29, 50, 19, 50, 70, 75, 52, 74])

In [63]:
np.histogram(a,bins=[0,50,100])

(array([6, 9]), array([  0,  50, 100]))

In [64]:
#np.corrcoef

In [66]:
salary=np.array([20000,40000,25000,35000,60000])
exp=np.array([1,3,2,4,2])
np.corrcoef(salary,exp)


array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

In [67]:
#np.isin searching multiple elment

In [68]:
a

array([25, 55, 32, 53, 20, 41, 57, 29, 50, 19, 50, 70, 75, 52, 74])

In [69]:
items=[10,20,30,40,50,60,70,80,90,100]
a[np.isin(a,items)]


array([20, 50, 50, 70])

In [71]:
#np.flip
a

array([25, 55, 32, 53, 20, 41, 57, 29, 50, 19, 50, 70, 75, 52, 74])

In [72]:
np.flip(a)

array([74, 52, 75, 70, 50, 19, 50, 29, 57, 41, 20, 53, 32, 55, 25])

In [73]:
b

array([[19, 10, 44, 40],
       [54, 77, 36, 45],
       [ 9, 33, 95, 16],
       [ 8,  1, 85, 57],
       [82, 70, 89, 83],
       [27, 53, 94, 80]])

In [75]:
np.flip(b)

array([[80, 94, 53, 27],
       [83, 89, 70, 82],
       [57, 85,  1,  8],
       [16, 95, 33,  9],
       [45, 36, 77, 54],
       [40, 44, 10, 19]])

In [77]:
np.flip(b,axis=0)

array([[27, 53, 94, 80],
       [82, 70, 89, 83],
       [ 8,  1, 85, 57],
       [ 9, 33, 95, 16],
       [54, 77, 36, 45],
       [19, 10, 44, 40]])

In [78]:
np.flip(b,axis=1)

array([[40, 44, 10, 19],
       [45, 36, 77, 54],
       [16, 95, 33,  9],
       [57, 85,  1,  8],
       [83, 89, 70, 82],
       [80, 94, 53, 27]])

In [80]:
#np.put
a

array([25, 55, 32, 53, 20, 41, 57, 29, 50, 19, 50, 70, 75, 52, 74])

In [81]:
np.put(a,[0,1],[110,530])

In [82]:
a

array([110, 530,  32,  53,  20,  41,  57,  29,  50,  19,  50,  70,  75,
        52,  74])

In [83]:
#np.delete
a

array([110, 530,  32,  53,  20,  41,  57,  29,  50,  19,  50,  70,  75,
        52,  74])

In [86]:
np.delete(a,0) #a,index

array([530,  32,  53,  20,  41,  57,  29,  50,  19,  50,  70,  75,  52,
        74])

In [87]:
np.delete(a,[0,2,4])

array([530,  53,  41,  57,  29,  50,  19,  50,  70,  75,  52,  74])

#set functions

In [91]:
#union1d
m=np.array([1,2,3,4,5])
n=np.array([3,4,5,6,7])
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [93]:
np.intersect1d(m,n)

array([3, 4, 5])

In [94]:
np.setdiff1d(m,n)

array([1, 2])

In [96]:
#np.setxor1d
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [100]:
#np.in1d(m,1)
m[np.in1d(m,1)]

array([1])

In [101]:
#np.clip

In [102]:
a

array([110, 530,  32,  53,  20,  41,  57,  29,  50,  19,  50,  70,  75,
        52,  74])

In [103]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 32, 53, 25, 41, 57, 29, 50, 25, 50, 70, 75, 52, 74])