In [2]:
#Creating Numpy Arrays
#np.array
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
#2D and 3D
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [4]:
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [6]:
#dtype
np.array([1,2,3],dtype=float)
np.array([1,2,3],dtype=bool)

array([ True,  True,  True])

In [8]:
#np.arange
np.arange(1,11,2)
np.arange(1,15,3)

array([ 1,  4,  7, 10, 13])

In [12]:
#with reshape
np.arange(16).reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [13]:
#np.ones and np.zeors
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
#np.random
np.random.random((3,4))

array([[0.6505935 , 0.18363278, 0.6623098 , 0.40820704],
       [0.67273456, 0.08241882, 0.93918858, 0.8308496 ],
       [0.86720265, 0.17807525, 0.38748772, 0.08503825]])

In [16]:
#np.linspace->linear space
np.linspace(-10,10,10,dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [17]:
#np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#Array Attributes

In [18]:
a1=np.arange(10,dtype=np.int32)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

In [19]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [20]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [21]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [22]:
#ndim
a3.ndim

3

In [24]:
#shape
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [25]:
#size
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [28]:
#itemsize(Bytes)
a1.itemsize
a3.itemsize

8

In [29]:
#dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


In [30]:
#Changin Datatype
#astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

In [33]:
#Array Operation
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)

a1


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [34]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [40]:
#Scalar Operation
#Arithmetic
a1 **2
a1 +5
a1-5
a1/5
a1%5


array([[0, 1, 2, 3],
       [4, 0, 1, 2],
       [3, 4, 0, 1]])

In [36]:
#relational
a2==15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [41]:
#Vector Operation
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

In [46]:
#Array Functions
a1=np.random.random((3,3))
a1=np.round(a1*100)
a1

array([[90., 39., 84.],
       [50., 81., 68.],
       [28., 78., 69.]])

In [50]:
#max/min/sum/prod
#0->col and 1> row
np.min(a1)
np.max(a2)
np.sum(a2)
np.prod(a1)

1.2236354859456e+16

In [55]:
#mean/median/std/Var
np.var(a1)
np.mean(a2)
np.std(a1)
np.median(a1)
np.var(a1,axis=0)
np.var(a1,axis=1)

array([518.        , 161.55555556, 473.55555556])

In [56]:
#Trigonometric functions
np.sin(a1)

array([[ 0.89399666,  0.96379539,  0.73319032],
       [-0.26237485, -0.62988799, -0.89792768],
       [ 0.27090579,  0.51397846, -0.11478481]])

In [58]:
#dot product
a2=np.arange(12).reshape(3,4)
a3=np.arange(12,24).reshape(4,3)
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [59]:
#log and exponents
np.exp(a1)
np.log(a1)

array([[4.49980967, 3.66356165, 4.4308168 ],
       [3.91202301, 4.39444915, 4.21950771],
       [3.33220451, 4.35670883, 4.2341065 ]])

In [63]:
#round/ceil/floor
import math
np.ceil(np.random.random((2,3))*100)

array([[72., 86., 94.],
       [16., 45., 29.]])

In [64]:
#Indexing and slicing
a1=np.arange(10)
a2=np.arange(12).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [65]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [70]:
a2[1,0]
a2[1,1]
a2[1,2]
a2[1,3]

7

In [71]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [72]:
a3[1,0,1]

5

In [73]:
a3[1,1,0]

6

In [74]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
a1[2:5:1]

array([2, 3, 4])

In [76]:
a1[2:5:2]

array([2, 4])

In [77]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [78]:
a2[0:2,1::2]

array([[1, 3],
       [5, 7]])

In [79]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [80]:
a2[1,::3]

array([4, 7])

In [81]:
a2[0,:]

array([0, 1, 2, 3])

In [83]:
a3=np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [84]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [85]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [86]:
a3[0,1,:]

array([3, 4, 5])

In [88]:
#Iterating
a1

for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [89]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [90]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [91]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [92]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [93]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [94]:
#Reshaping
#Transpose
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [95]:
#ravel
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [97]:
#Stacking
#horizontal stacking
a4=np.arange(12).reshape(3,4)
a5=np.arange(12,24).reshape(3,4)
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [98]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [99]:
#Vertical Stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [100]:
#Spliting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [101]:
np.hsplit(a4,4)

[array([[0],
        [4],
        [8]]), array([[1],
        [5],
        [9]]), array([[ 2],
        [ 6],
        [10]]), array([[ 3],
        [ 7],
        [11]])]

In [102]:
#Vertical spliting
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [108]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]